image: maven:3-alpine

before_script:
  - echo $JAVA_HOME
  - java -version
  - mvn -version

stages:
  - test

execute-tests:
  stage: test
  script:
    - mvn clean test -T 1C -U --fail-at-end --batch-mode -Pcssnexus