image: maven:latest

before_script:
  - echo $JAVA_HOME
  - java -version
  - mvn -version

stages:
  - test

# -T 1C -U --fail-at-end --batch-mode -Pcssnexus
execute-tests:
  stage: test
  script:
    - mvn test