apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: '2017-09-16T11:23:33Z'
  labels:
    app: openjdk18-web-basic-s2i
    application: reaper-agent
    template: openjdk18-web-basic-s2i
    xpaas: 1.0.0
  name: reaper-agent
  namespace: reaper
  resourceVersion: '108283842'
  selfLink: /oapi/v1/namespaces/reaper/buildconfigs/reaper-agent
  uid: 7967833a-9ad1-11e7-8e2b-123713f594ec
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'reaper-agent:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://gitlab.com/reaper-monitoring-alerting/reaper-agent.git'
    sourceSecret:
      name: michaelcouck-0-pxs
    type: Git
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: 'redhat-openjdk18-openshift:1.0'
        namespace: openshift
    type: Source
  triggers:
    - github:
        secret: michaelcouck-0-pxs
      type: GitHub
    - generic:
        secret: SdkKqBBn
      type: Generic
    - imageChange:
        lastTriggeredImageID: >-
          registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift@sha256:671f386241987946c189838af8ed4aca2b83a56d63bfff638fbfb47d5b1b8248
      type: ImageChange
    - type: ConfigChange
status:
  lastVersion: 10
